name: Artificial Intelligence - GenerAtive Artificial Intelligence - Tool - Production Monitor
type: Tech-3
data:
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 639699692
          name: hkust-nlp/ceval
        - id: 642020947
          name: RUCAIBox/POPE
