name: Artificial Intelligence - production monitor
type: Tech-1
data:
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 639699692
          name: hkust-nlp/ceval
        - id: 642020947
          name: RUCAIBox/POPE
