name: Cloud Native - App Definition and Development - Application Definition & Image Build
type: Tech-2
data:
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 233809604
          name: artifacthub/hub
        - id: 236095576
          name: backstage/backstage
        - id: 138544269
          name: buildpacks/pack
        - id: 173207060
          name: vmware-tanzu/carvel-ytt
        - id: 36098429
          name: habitat-sh/habitat
        - id: 126647111
          name: cloud-ark/kubeplus
        - id: 226084465
          name: devfile/api
        - id: 145153231
          name: loft-sh/devspace
        - id: 15045751
          name: docker/compose
        - id: 32935745
          name: eclipse/che
        - id: 429510684
          name: gefyrahq/gefyra
        - id: 302322
          name: gradle/gradle
        - id: 43723161
          name: helm/helm
        - id: 119419195
          name: GoogleContainerTools/kaniko
        - id: 303758423
          name: konveyor/community
        - id: 198856247
          name: replicatedhq/kots
        - id: 368314469
          name: krator-rs/krator
        - id: 218249592
          name: kubermatic/kubecarrier
        - id: 450404132
          name: teamcode-inc/kubeorbit
        - id: 276822250
          name: kubevela/kubevela
        - id: 76686583
          name: kubevirt/kubevirt
        - id: 158545617
          name: kudobuilder/kudo
        - id: 159242360
          name: kubernetes-sigs/kui
        - id: 101875675
          name: uselagoon/lagoon
        - id: 373775141
          name: kubeshop/monokle
        - id: 311269921
          name: nocalhost/nocalhost
        - id: 192779991
          name: vmware-tanzu/octant
        - id: 143846881
          name: okteto/okteto
        - id: 191840044
          name: oam-dev/spec
        - id: 62855546
          name: openservicebrokerapi/servicebroker
        - id: 17372733
          name: OAI/OpenAPI-Specification
        - id: 120650407
          name: operator-framework/operator-sdk
        - id: 8966356
          name: hashicorp/packer
        - id: 109145553
          name: containers/podman
        - id: 155893691
          name: getporter/porter
        - id: 362675427
          name: alibaba/sealer
        - id: 264246502
          name: serverlessworkflow/specification
        - id: 91674936
          name: apache/servicecomb-java-chassis
        - id: 358693091
          name: shipwright-io/community
        - id: 118654121
          name: GoogleContainerTools/skaffold
        - id: 100131598
          name: solo-io/squash
        - id: 197374067
          name: grafana/tanka
        - id: 82933315
          name: telepresenceio/telepresence
        - id: 143896900
          name: tilt-dev/tilt
