name: Cloud Native - App Definition and Development - Database
type: Tech-2
data:
  labels:
    - ':companies/apple/foundationdb'
    - ':companies/cloudera/hadoop'
    - ':companies/cratedb/cratedb'
    - ':companies/databend/databend'
    - ':companies/google/vitess'
    - ':companies/imply/druid'
    - ':companies/mariadb/mariadb'
    - ':companies/meta/cassandra'
    - ':companies/neo4j/neo4j'
    - ':companies/pingcap/tikv'
    - ':companies/vk/tarantool'
    - ':companies/weaviate/weaviate'
    - ':companies/yandex/clickhouse'
  platforms:
    - name: GitHub
      type: Code Hosting
      repos:
        - id: 62117818
          name: apache/carbondata
        - id: 31006158
          name: apache/ignite
        - id: 2649214
          name: arangodb/arangodb
        - id: 51290852
          name: bigchaindb/bigchaindb
        - id: 3180703
          name: couchbase/manifest
        - id: 83363132
          name: CrunchyData/postgres-operator
        - id: 125824259
          name: xtdb/xtdb
        - id: 307894865
          name: alibaba/graphscope
        - id: 1050944
          name: infinispan/infinispan
        - id: 24494032
          name: mysql/mysql-server
        - id: 146459443
          name: vesoft-inc/nebula
        - id: 36778364
          name: attic-labs/noms
        - id: 7083240
          name: orientechnologies/orientdb
        - id: 30753733
          name: percona/percona-server
        - id: 40127179
          name: pilosa/pilosa
        - id: 927442
          name: postgres/postgres
        - id: 166515022
          name: trinodb/trino
        - id: 156018
          name: redis/redis
        - id: 6452529
          name: rethinkdb/rethinkdb
        - id: 151700458
          name: scalar-labs/scalardb
        - id: 183834521
          name: schemahero/schemahero
        - id: 28449431
          name: scylladb/scylla
        - id: 163387337
          name: seata/seata
        - id: 49876476
          name: apache/shardingsphere
        - id: 396856161
          name: authzed/spicedb
        - id: 43884372
          name: sorintlab/stolon
        - id: 196353673
          name: taosdata/TDengine
        - id: 41986369
          name: pingcap/tidb
        - id: 2445970
          name: voltdb/voltdb
        - id: 105944401
          name: YugaByte/yugabyte-db
