name: Conda Forge
description: A staging area for conda recipes to become conda-forge feedstocks
description_zh: conda 包的暂存区，用于成为 conda-forge 饲料库
type: Project
data:
  platforms:
    - name: GitHub
      type: Code Hosting
      orgs:
        - id: 11897326
          name: conda-forge
