name: containerd
description: An open and reliable container runtime
description_zh: 一个开放且可靠的容器运行时
type: Project
data:
  platforms:
    - name: GitHub
      type: Code Hosting
      orgs:
        - id: 14037953
          name: containerd
