export const subdivisionAliasMap = new Map<string, string[]>([
  ['WS-TU', ['Upolu']],
  ['SG-03', ['North West Community Development Council']],
  ['SC-16', ['La Riviere Anglaise']],
  ['FR-PM', ['Saint-Pierre']],
  ['AG-04', ['Antigua']],
  ['MR-14', ['Nouakchott']],
  ['VC-04', ['St. George']],
  ['CD-TA', ['Katanga']],
  ['GB-SCT', ['Ayrshire']],
  ['LU-ME', ['Canton of Mersch']],
  ['MH-T', ['Majuro Atoll']],
  ['MH-L', ['Kili']],
  ['KR-42', ['Gangwon-do']],
  ['SO-NU', ['Nugal']],
  ['SO-JH', ['Lower Juba']],
  ['SB-GU', ['Guadalcanal Province', 'Honiara']],
  ['SI-070', ['Upravna enota Maribor', 'Administrative unit Maribor']],
  ['BS-FP', ['Freeport']],
  ['BS-NP', ['N.P']],
  ['TL-DI', ['Dili']],
  ['TL-LI', ['Liquica']],
  ['MT-27', ['Marsascala']],
  ['MT-30', ['Mellieha']],
  ['MT-64', ['Zabbar']],
  ['ML-BKO', ['Bamako Capital District']],
  ['TG-M', ['Région maritime']],
  ['BN-BM', ['Daerah Brunei-Muara']],
  ['RW-01', ['Kigali City']],
  ['HU-CS', ['Csongrád']],
  ['GH-NE', ['Northern East Region']],
  ['ZM-06', ['Northwestern Province']],
  ['PG-NSB', ['Autonomous Region of Bougainville']],
  ['SL-N', ['Northern Province, Sierra Leone']],
  ['SL-S', ['Southern Province, Sierra Leone']],
  ['GA-8', ['Ogooue-Maritime']],
  ['GA-2', ['Haut-Ogooue']],
  ['TM-S', ['Ashgabat', 'Ashgabat City']],
  ['MZ-MPM', ['Cidade de Maputo']],
  ['MZ-Q', ['Zambezia Province']],
  ['VU-SEE', ['Shefa Province', 'Shefa']],
  ['VU-PAM', ['Penama Province', 'Penama']],
  ['VU-TAE', ['Tafea Province', 'Tafea']],
  ['KG-GO', ['Osh City']],
  ['MW-S', ['Southern Region, Malawi']],
  ['MW-C', ['Central Region, Malawi']],
  ['MW-N', ['Northern Region, Malawi']],
  ['KG-Y', ['Issyk-Kul Region']],
  ['KG-C', ['Bishkek City']],
  ['SD-KN', ['North Kurdufan']],
  ['SD-GZ', ['Al Jazirah']],
  ['NG-FC', ['Federal Capital Territory']],
  ['NG-OG', ['Ìpínlẹ̀ Ògùn']],
  ['IS-6', ['Northeastern Region']],
  ['IS-2', ['Southern Peninsula']],
  ['IS-1', ['Capital Region']],
  ['IS-7', ['Sveitarf��lagið Hornafjörður']],
  ['RS-VO', ['VOJ', 'Војводина', 'SER']],
  ['ZA-NW', ['North West']],
  ['ZA-GP', ['GT']],
  ['ZA-KZN', ['NL']],
  ['MM-18', ['Naypyidaw Union Territory']],
  ['MM-06', ['ရန်ကုန်တိုင်းဒေသကြီး']],
  ['MM-04', ['မန္တလေးတိုင်းဒေသကြီး']],
  ['MU-PW', ['Quatre Bornes']],
  ['MU-RO', ['Rodrigues']],
  ['MU-RR', ['Rivière Noire District']],
  ['GE-AJ', ['Adjara']],
  ['GE-KA', ['Kakheti']],
  ['GE-RL', ['Racha-Lechkhumi and Lower Svaneti']],
  ['ME-05', ['Opština Budva']],
  ['ME-08', ['Herceg Novi Municipality']],
  ['ME-20', ['Opština Ulcinj']],
  ['CI-AB', ["District Autonome d'Abidjan"]],
  ['CI-YM', ['District Autonome du Yamoussoukro', 'Yamoussoukro District']],
  ['BT-12', ['Chukha']],
  ['BT-42', ['Mongar']],
  ['BT-15', ['ཐིམ་ཕུ་རྫོང་ཁག']],
  ['GM-B', ['Banjul City Council', 'Kanifing', 'Kanifing Municipal Council', 'Brikama']],
  ['NZ-WGN', ['Wellington']],
  ['NZ-MWT', ['Manawatu-Wanganui']],
  ['NZ-NTL', ['North Island']],
  ['NZ-STL', ['South Island']],
  ['HT-OU', ["Département de l'Ouest"]],
  ['HT-ND', ['Département du Nord']],
  ['HT-SE', ['Département du Sud-Est']],
  ['HT-NI', ['Département des Nippes']],
  ['AO-MAL', ['Malanje Province']],
  ['AO-LNO', ['Lunda Norte Province']],
  ['AO-LSU', ['Lunda Sul Province']],
  ['AO-HUI', ['Huila Province']],
  ['BW-NW', ['North-West District']],
  ['BW-SE', ['South-East District', 'South-East']],
  ['BW-NE', ['North-East District']],
  ['GL-SM', ['Sermersooq Municipality']],
  ['GL-QE', ['Kitaa', 'Vestgrønland']],
  ['GL-KU', ['Kujalleq Municipality']],
  ['UY-RO', ['Departamento de Rocha']],
  ['UY-MO', ['Departamento de Montevideo']],
  ['UY-RV', ['Departamento de Rivera']],
  ['UY-CL', ['Departamento de Cerro Largo']],
  ['AL-11', ['Tirana County', 'Tirana', 'Qarku i Tiranës']],
  ['AL-02', ['Durres']],
  ['JM-08', ['St. James Parish']],
  ['JM-02', ['St. Andrew Parish']],
  ['JM-03', ['St. Thomas Parish']],
  ['JM-14', ['St. Catherine Parish']],
  ['JM-06', ['St. Ann Parish']],
  ['ER-DU', ['Southern Red Sea']],
  ['ER-MA', ['Maekel Region', 'Maekel']],
  ['ER-AN', ['Northern Red Sea', 'Northen Red Sea Region']],
  ['TD-MO', ['Mayo-Kebbi Ouest']],
  ['TD-HL', ['Hadjer-Lamis']],
  ['TD-LR', ['Logone Oriental']],
  ['TD-ND', ["N'Djamena"]],
  ['TD-ME', ['Mayo-Kebbi Est']],
  ['RS-KM', ['Prizren District', 'District of Mitrovica', 'District of Pristina',
    'District of Gjilan', 'District of Peja']],
  ['IL-D', ['South District']],
  ['IL-M', ['Center District', 'מחוז המרכז']],
  ['IL-Z', ['North District']],
  ['IL-TA', ['מחוז תל אביב']],
  ['NL-NB', ['North Brabant', 'Sprang-Capelle']],
  ['NL-FR', ['Friesland']],
  ['NL-NH', ['North Holland']],
  ['NL-ZH', ['South Holland']],
  ['GN-C', ['Conakry Region']],
  ['GN-F', ['Faranah Region']],
  ['GN-K', ['Kindia Region']],
  ['GN-N', ['Nzérékoré Region']],
  ['GN-B', ['Boké Region']],
  ['MV-08', ['Thaa Atoll']],
  ['MV-24', ['Shaviyani Atoll']],
  ['MV-20', ['Baa Atoll']],
  ['MV-26', ['Male Atoll', 'Kaafu Atoll']],
  ['MV-MLE', ['Malé']],
  ['BF-03', ['Center']],
  ['BF-07', ['Central-South']],
  ['BF-06', ['Central-West']],
  ['BF-13', ['Southwest']],
  ['BF-09', ['Upper-Basins']],
  ['SN-DK', ['Région de Dakar']],
  ['SN-TH', ['Région de Thiès']],
  ['SN-DB', ['Région de Diourbel']],
  ['SN-SL', ['Région de Saint Louis']],
  ['SN-SE', ['Région de Sédhiou']],
  ['DK-84', ['Capital Region of Denmark']],
  ['DK-82', ['Central Denmark Region']],
  ['DK-81', ['North Denmark Region']],
  ['DK-85', ['Region Zealand']],
  ['DK-83', ['Region of Southern Denmark']],
  ['JP-07', ['福島県']],
  ['JP-13', ['東京都', 'Toukyou']],
  ['JP-45', ['宮崎県']],
  ['JP-26', ['京都府']],
  ['AE-AZ', ['أبو ظبي']],
  ['AE-DU', ['دبي']],
  ['AE-RK', ['Ras al-Khaimah']],
  ['AE-AJ', ['Ajman', 'Ajman Emirate']],
  ['QA-DA', ['Doha Municipality', 'Doha']],
  ['QA-KH', ['Al Khor and Al Thakhira Municipality', 'Al Khor and Al Thakhira']],
  ['QA-RA', ['Al Rayyan Municipality']],
  ['LK-3', ['Southern']],
  ['LK-1', ['Western']],
  ['LK-5', ['Eastern']],
  ['LK-2', ['වයඹ පළාත, ශ්‍රී ලංකාව']],
  ['LK-6', ['බස්නාහිර පළාත, ශ් රී ලංකාව']],
  ['AT-7', ['Tyrol']],
  ['AT-9', ['Vienna']],
  ['AT-4', ['Upper Austria']],
  ['AT-2', ['Carinthia']],
  ['AT-6', ['Styria']],
  ['AT-3', ['Lower Austria']],
  ['BH-13', ['Muḥāfaẓat al-ʿĀṣimah', 'Capital Governorate', '[no name]']],
  ['BH-15', ['Muharraq Governorate', 'Muḥāfaẓat al-Muḥarraq']],
  ['BH-17', ['Northern Governorate', 'Ash Shamālīyah']],
  ['TJ-KT', ['Khatlon Province']],
  ['TJ-GB', ['Gorno-Badakhshan Autonomous Province', 'Gorno-Badakhshan Autonomous Region']],
  ['TJ-SU', ['Vilojati Suƣd', 'Sughd Province']],
  ['TJ-RA', ['Districts of Republican Subordination']],
  ['PK-IS', ['Islamabad Capital Territory', 'Federally Administered Tribal Areas']],
  ['PK-JK', ['Azad Kashmir']],
  ['PK-BA', ['Baluchistan']],
  ['PK-PB', ['پنجاب']],
  ['PK-SD', ['سندھ']],
  ['BA-BRC', ['Brčko District']],
  ['BA-SRP', ['Serb Republic', 'SR', 'Republica Srpska']],
  ['BA-BIH', ['Federation of Bosnia and Herzegovina', 'BH', 'BR', 'Federation of Bosnia & Herzegovina']],
  ['EC-B', ['Bolivar']],
  ['EC-R', ['Los Rios']],
  ['EC-W', ['Islas Galápagos', 'Galápagos Islands']],
  ['EC-SD', ['Santo Domingo de los Tsachilas']],
  ['EC-S', ['Morona-Santiago']],
  ['EC-U', ['Sucumbios']],
  ['LV-022', ['Cesis']],
  ['LV-RIX', ['Riga']],
  ['LV-JUR', ['Jurmala']],
  ['LV-LPX', ['Liepaja']],
  ['LV-112', ['South Kurzeme Municipality']],
  ['LV-REZ', ['Rezekne']],
  ['LV-050', ['Kuldiga']],
  ['BO-B', ['Beni Department']],
  ['BO-S', ['Departamento de Santa Cruz']],
  ['BO-P', ['Potosi Department', 'Departamento de Potosí']],
  ['BO-L', ['Departamento de La Paz']],
  ['BO-C', ['Departamento de Cochabamba']],
  ['BO-T', ['Departamento de Tarija']],
  ['MD-CL', ['Raionul Călărași']],
  ['MD-BA', ['Balti']],
  ['MD-ED', ['Edineţ District']],
  ['MD-CU', ['Chisinau']],
  ['MD-SN', ['Administrative-Territorial Units of the Left Bank of the Dniester', 'Transnistria autonomous territorial unit']],
  ['MD-OR', ['Raionul Orhei']],
  ['UG-N', ['Northern Region', 'Mkoa wa Kaskazini']],
  ['UG-E', ['Eastern Region']],
  ['UG-W', ['Western Region', 'Mkoa wa Magharibi']],
  ['UG-C', ['Central Region', 'Mkoa wa Kati']],
  ['CY-06', ['Kyrenia']],
  ['CY-04', ['Famagusta']],
  ['CY-01', ['Nicosia']],
  ['CY-02', ['Limasol', 'Limassol']],
  ['CY-03', ['Larnaca']],
  ['CY-05', ['Paphos']],
  ['PA-8', ['Provincia de Panamá', 'PN']],
  ['PA-4', ['Provincia de Chiriquí', 'CH']],
  ['PA-7', ['LS']],
  ['PA-3', ['CL']],
  ['PA-6', ['HE']],
  ['PA-5', ['DA']],
  ['PT-20', ['Azores', 'Açores']],
  ['PT-11', ['Lisbon']],
  ['PT-30', ['Madeira', 'Madeira Island']],
  ['PT-09', ['Distrito da Guarda']],
  ['PT-15', ['Setubal']],
  ['PT-07', ['Distrito de Évora']],
  ['SV-SS', ['SVSS']],
  ['SV-US', ['SVUS']],
  ['SV-SA', ['SVSA']],
  ['SV-SM', ['SVSM']],
  ['SV-LI', ['SVLI', 'SVLP', 'SVLL']],
  ['SV-SV', ['SVSI']],
  ['SV-CH', ['SVCH']],
  ['TZ-06', ['Unguja South Region']],
  ['TZ-26', ['Mkoa wa Simiyu']],
  ['TZ-04', ['Mkoa wa Iringa']],
  ['TZ-11', ['Unguja South Region', 'Zanzibar South & Central']],
  ['TZ-02', ['Dar es Salam', 'salaam']],
  ['TZ-15', ['Zanzibar Urban/West']],
  ['TZ-03', ['Mkoa wa Dodoma']],
  ['CU-09', ['Camaguey']],
  ['CU-14', ['Guantanamo']],
  ['CU-11', ['Holguin']],
  ['CU-08', ['Ciego de Avila']],
  ['CU-99', ['Isle of Youth']],
  ['CU-01', ['Pinar del Rio']],
  ['CU-07', ['Sancti Spiritus']],
  ['CU-03', ['Havana']],
  ['PE-LIM', ['Gobierno Regional de Lima', 'Lima Province', 'Provincia de Lima']],
  ['PE-CAL', ['Callao', 'Constitutional Province of Callao', 'Callao Region']],
  ['PE-APU', ['Apurimac']],
  ['PE-HUC', ['Huanuco']],
  ['TT-TUP', ['Tunapuna/Piarco Regional Corporation']],
  ['TT-SFO', ['San Fernando City Corporation']],
  ['TT-SJL', ['San Juan-Laventille Regional Corporation']],
  ['TT-POS', ['Port of Spain Corporation']],
  ['TT-PRT', ['Princes Town Regional Corporation']],
  ['TT-MRC', ['Mayaro Rio Claro Regional Corporation']],
  ['TT-CHA', ['Chaguanas Borough Corporation']],
  ['TT-CTT', ['Couva-Tabaquite-Talparo Regional Corporation']],
  ['CD-KE', ['Kasai-Oriental', 'Kasai Oriental']],
  ['CD-SK', ['South-Kivu', 'South Kivu']],
  ['CD-HU', ['Upper Uele', 'Lower Uele']],
  ['CD-NK', ['North-Kivu', 'North Kivu']],
  ['CD-KC', ['Kasai-Central', 'Kasaï-Central']],
  ['DE-SN', ['Saxony']],
  ['DE-HE', ['Hesse']],
  ['DE-BY', ['Bavaria']],
  ['DE-NI', ['Lower Saxony']],
  ['DE-ST', ['Saxony-Anhalt']],
  ['DE-RP', ['Rhineland-Palatinate']],
  ['DE-MV', ['Mecklenburg-West Pomerania']],
  ['DE-TH', ['Thuringia']],
  ['DE-NW', ['North Rhine-Westphalia']],
  ['KE-28', ['Coast']],
  ['KE-30', ['Nairobi County', 'Nairobi']],
  ['KE-29', ['Muranga County']],
  ['KE-42', ['Trans-Nzoia County']],
  ['KE-39', ['Taita-Taveta County']],
  ['KE-05', ['Elgeyo-Marakwet County']],
  ['KE-08', ['Rift Valley']],
  ['KE-13', ['Eastern']],
  ['OM-DA', ['Ad Dakhiliyah Governorate', 'Ad Dakhiliyah ‍Governorate']],
  ['OM-BU', ['Al Buraymi Governorate']],
  ['OM-WU', ['Al Wusta Governorate']],
  ['OM-ZA', ['Ad Dhahirah Governorate']],
  ['OM-BJ', ['Al Batinah South Governorate']],
  ['OM-SJ', ['Ash Sharqiyah South Governorate']],
  ['OM-MA', ['محافظة مسقط']],
  ['OM-BS', ['Al Batinah North Governorate']],
  ['OM-SS', ['Ash Sharqiyah North Governorate']],
  ['BD-D', ['খুলনা বিভাগ']],
  ['BD-B', ['চট্টগ্রাম বিভাগ']],
  ['BD-A', ['Barisal Division', 'বরিশাল বিভাগ', 'Barisāl']],
  ['BD-E', ['রাজশাহী বিভাগ']],
  ['BD-C', ['ঢাকা বিভাগ']],
  ['BD-G', ['সিলেট বিভাগ']],
  ['BD-H', ['ময়মনসিংহ বিভাগ']],
  ['KW-AH', ['Al Ahmadi Governorate', 'sharq']],
  ['KW-FA', ['Al Farwaniyah Governorate']],
  ['KW-JA', ['Al Jahra Governorate']],
  ['KW-KU', ['Al Asimah Governate', 'Al Asimah']],
  ['KW-MU', ['Mubarak Al-Kabeer Governorate']],
  ['KW-HA', ['Hawalli', 'Hawalli Governorate']],
  ['MN-1', ['Ulaanbaatar', 'Улаанбаатар', 'Ulaanbaatar Hot']],
  ['MN-041', ['Khovsgol', 'Hövsgöl']],
  ['MN-057', ['Zavkhan Province', 'Dzavhan']],
  ['MN-071', ['Bayan-Ölgii']],
  ['MN-065', ['Govi-Altai', 'Govĭ-Altay']],
  ['MN-053', ['Ömnögovi', 'Ömnögovĭ']],
  ['MN-037', ['Darkhan-Uul', 'Darhan uul']],
  ['MN-035', ['Orkhon', 'Orhon', 'Orkhon Province']],
  ['NO-54', ['Troms og Finnmark fylke', 'Finnmark', 'Troms']],
  ['NO-38', ['Vestfold', 'Telemark']],
  ['NO-46', ['Hordaland']],
  ['NO-30', ['Akershus', 'Østfold', 'Buskerud']],
  ['NO-50', ['Sogn og Fjordane']],
  ['NO-18', ['Nordland']],
  ['NO-03', ['Oslo']],
  ['NO-11', ['Rogaland']],
  ['NO-42', ['Agder']],
  ['NO-34', ['Innlandet']],
  ['NO-15', ['Møre og Romsdal']],
  ['NO-21', ['Svalbard']],
  ['NO-22', ['Jan Mayen']],
  ['NI-ES', ['Esteli']],
  ['NI-SJ', ['Rio San Juan', 'RS']],
  ['NI-AN', ['North Caribbean Coast Autonomous Region', 'RA']],
  ['NI-AS', ['South Caribbean Coast Autonomous Region']],
  ['NI-MD', ['MG']],
  ['NI-CI', ['CN']],
  ['NI-MN', ['CD']],
  ['NI-LE', ['Leon']],
  ['NI-CN', ['CN']],
  ['TR-33', ['İçel']],
  ['TR-34', ['Istanbul']],
  ['TR-03', ['Afyon']],
  ['TR-30', ['Hakkari']],
  ['TR-81', ['Duzce']],
  ['TR-76', ['Igdir', 'Iğdır']],
  ['TR-63', ['Şanliurfa', 'Şanlıurfa']],
  ['TR-46', ['Kahraman Maras', 'Kahramanmaraş']],
  ['TR-78', ['Karabuk', 'Karabük']],
  ['TR-73', ['Sirnak', 'Şırnak']],
  ['CR-A', ['Provincia de Alajuela', 'AL']],
  ['CR-C', ['Provincia de Cartago', 'CA']],
  ['CR-G', ['Provincia de Guanacaste', 'GU']],
  ['CR-H', ['HE']],
  ['CR-L', ['Provincia de Limón', 'LI']],
  ['CR-P', ['Provincia de Puntarenas', 'PU']],
  ['KP-03', ['North Pyongan']],
  ['KP-02', ["South P'yŏngan", 'South Pyongan']],
  ['KP-07', ['Kangwŏn', 'Kangwon']],
  ['KP-09', ['North Hamgyong']],
  ['KP-13', ['Rason']],
  ['KP-01', ['Pyongyang', 'P’yŏngyang']],
  ['KP-06', ['North Hwanghae']],
  ['LB-NA', ['Nabatiyeh Governorate', 'Nabatieh Governorate']],
  ['LB-AS', ['North Governorate']],
  ['LB-BA', ['Beirut', 'Beirut Governorate']],
  ['LB-JL', ['Mount Lebanon Governorate', 'Jabal Lubnan', 'Keserwan-Jbeil Governorate']],
  ['LB-BI', ['Beqaa Governorate']],
  ['LB-JA', ['South Governorate']],
  ['BE-VLG', ['Flanders', 'Région Flamande', 'Flemish Region', 'Meeuwen-Gruitrode']],
  ['BE-WAL', ['Walloon Region', 'Wallonia', 'Région Wallonne']],
  ['BE-BRU', ['Brussels', 'Brussel', 'Brussels Region', 'Bruxelles']],
  ['AM-AG', ['Aragatsotn Province']],
  ['AM-AR', ['Ararat Province']],
  ['AM-AV', ['Armavir Province']],
  ['AM-ER', ['Yerevan']],
  ['AM-GR', ['Gegharkunik Province']],
  ['AM-KT', ['Kotayk Province']],
  ['AM-LO', ['Lori Province']],
  ['AM-SU', ['Syunik Province']],
  ['AM-TV', ['Tavush Province']],
  ['AM-VD', ['Vayots Dzor Province']],
  ['AM-SH', ['Shirak Province']],
  ['PH-14', ['Rehiyong Awtonomo sa Muslim na Mindanao', 'Autonomous Region Of Muslim Mindanao', 'Bangsamoro Autonomous Region in Muslim Mindanao']],
  ['PH-10', ['North Mindanao']],
  ['PH-07', ['Gitnang Kabisayaan', 'Gitnáng Luzon']],
  ['PH-00', ['Kalakhang Maynila', 'Metro Manila']],
  ['PH-05', ['Kabikulan']],
  ['PH-11', ['Rehiyon ng Davao']],
  ['PH-15', ['Cordillera Admin Region']],
  ['CH-LU', ['Canton of Lucerne', 'Lucerne', 'Kanton Luzern']],
  ['CH-BS', ['Basel City']],
  ['CH-ZH', ['Zurich']],
  ['CH-SG', ['St Gallen', 'St. Gallen']],
  ['CH-GE', ['Geneva']],
  ['CH-VD', ['Waadt']],
  ['CH-BE', ['Canton of Bern']],
  ['CH-ZG', ['Canton of Zug']],
  ['CH-GR', ['Grisons']],
  ['MY-14', ['Federal Territory of Kuala Lumpur', 'Wilayah Persekutuan']],
  ['MY-07', ['Penang', 'Pulau Pinang']],
  ['MY-04', ['Malacca', 'Melaka']],
  ['MY-16', ['Putrajaya', 'Putrajaya Federal Territory']],
  ['MY-01', ['Johore', "Johor Darul Ta'zim"]],
  ['MY-15', ['Labuan', 'Labuan Federal Territory']],
  ['MY-05', ['Negri Sembilan']],
  ['MY-10', ['Sepang']],
  ['CM-AD', ['Adamawa Region', "Région de l'Adamaoua", 'Adamawa']],
  ['CM-CE', ['Région du Centre']],
  ['CM-LT', ['Région du Littoral']],
  ['CM-SW', ['Southwest Region', 'Southwest']],
  ['CM-EN', ['Far-North']],
  ['CM-OU', ["Région de l'Ouest"]],
  ['CM-NW', ['Région du Nord-Ouest', 'Northwest', 'Northwest Region']],
  ['AZ-SR', ['Shirvan-Salyan']],
  ['AZ-NX', ['Nakhichevan Autonomous Republic', 'Nakhchivan Autonomous Republic']],
  ['AZ-ABS', ['Absheron-Khizi']],
  ['AZ-SA', ['Sheki-Zaqatala']],
  ['AZ-LA', ['Lankaran-Astara']],
  ['AZ-QBA', ['Quba-Khachmaz']],
  ['AZ-BA', ['Baku', 'Baku Ekonomic Zone']],
  ['AZ-QAX', ['Qakh']],
  ['AZ-AGM', ['Askeran Province']],
  ['AZ-GA', ['Ganja-Dashkasan']],
  ['AZ-DAS', ['Ganja-Dashkasan']],
  ['KH-12', ['PP', 'ភ្នំពេញ']],
  ['KH-1', ['BB']],
  ['KH-8', ['KD']],
  ['KH-13', ['PV']],
  ['KH-14', ['PY']],
  ['KH-15', ['PS']],
  ['KH-16', ['Rôtkiri']],
  ['KH-17', ['Siemreab']],
  ['KH-18', ['SE']],
  ['KH-19', ['Steung Treng Province', 'Stueng Traeng']],
  ['KH-20', ['SR']],
  ['KH-21', ['Takéo Province', 'Takev']],
  ['KH-22', ['BM']],
  ['KH-23', ['KB']],
  ['KH-24', ['Pailin']],
  ['KH-25', ['TB']],
  ['KH-10', ['Kratié Province', 'Kracheh']],
  ['ET-SW', ['South West Ethiopia Peoples']],
  ['ET-BE', ['Benishangul-Gumuz']],
  ['ET-GA', ['Gambella']],
  ['ET-SO', ['Somali Region']],
  ['ET-OR', ['Oromia Region']],
  ['ET-HA', ['Harar', 'Harari']],
  ['ET-AM', ['Amhara Region', 'አማራ', 'Amhara']],
  ['ET-SN', ['Southern Nations, Nationalities, and Peoples', 'ደቡብ ብሔሮች ብሔረሰቦችና ሕዝቦች ክልል', 'Southern Nations, Nationalities and Peoples']],
  ['ET-AA', ['አዲስ አበባ']],
  ['BY-BR', ['Brest Region', 'Brest', 'Brest Province']],
  ['BY-HO', ['Gomel Region', 'Homel']],
  ['BY-HM', ['Minsk', 'Minsk Province']],
  ['BY-HR', ['Hrodna Region', 'Hrodna', 'Grodno Province']],
  ['BY-MA', ['Mogilev Region', 'Mahilyow']],
  ['BY-MI', ['Minsk Region']],
  ['BY-VI', ['Vitebsk Region', 'Vitsyebsk']],
  ['SY-LA', ['Latakia Governorate']],
  ['SY-HA', ['Al-Hasaka Governorate', 'Al-Hasakah Governorate']],
  ['SY-RA', ['Raqqa Governorate']],
  ['SY-SU', ['As-Suwayda Governorate']],
  ['SY-DR', ["Dar'ā"]],
  ['SY-DY', ['Deir Ez-Zor Governorate']],
  ['SY-DI', ['Damascus Governorate']],
  ['SY-ID', ['Idlib Governorate']],
  ['SY-RD', ['Rif Dimashq Governorate']],
  ['SY-TA', ['Tartus Governorate']],
  ['SY-HL', ['Aleppo Governorate']],
  ['SY-HM', ['Hama Governorate']],
  ['SY-HI', ['Homs Governorate']],
  ['LA-AT', ['AP']],
  ['LA-BL', ['Bolikhamsai Province']],
  ['LA-CH', ['CS']],
  ['LA-HO', ['HP']],
  ['LA-KH', ['KM']],
  ['LA-LM', ['PL']],
  ['LA-LP', ['ຫຼວງພະບາງ', 'ແຂວງຫຼວງພະບາງ', 'Luang Prabang Province']],
  ['LA-OU', ['OD']],
  ['LA-PH', ['SK']],
  ['LA-SL', ['XH']],
  ['LA-SV', ['VC']],
  ['LA-VT', ['VB']],
  ['LA-XA', ['Sainyabuli Province']],
  ['LA-XS', ['XB']],
  ['LA-XI', ['XK']],
  ['LA-XE', ['XK']],
  ['KR-43', ['North Chungcheong']],
  ['KR-41', ['경기도']],
  ['KR-49', ['제주특별자치도', 'Jeju-do']],
  ['KR-44', ['South Chungcheong']],
  ['KR-47', ['North Gyeongsang']],
  ['KR-50', ['Sejong City', 'Sejong-si']],
  ['KR-48', ['South Gyeongsang']],
  ['KR-46', ['South Jeolla']],
  ['KR-45', ['North Jeolla', 'Jeonbuk State']],
  ['KR-29', ['광주광역시']],
  ['KR-27', ['대구광역시']],
  ['KR-11', ['서울특별시']],
  ['KR-31', ['Ulsan-gwangyeoksi']],
  ['TN-12', ['Ariana Governorate', "Gouvernorat de l'Ariana", 'Ariana']],
  ['TN-51', ['Gouvernorat de Sousse', 'سوسة']],
  ['TN-42', ['Kassérine Governorate']],
  ['TN-43', ['Sidi Bou Zid Governorate']],
  ['TN-11', ['تونس']],
  ['TN-14', ['Manubah Governorate', 'La Manouba', 'Manouba']],
  ['TN-23', ['Gouvernorat de Bizerte']],
  ['TN-53', ['Gouvernorat de Mahdia']],
  ['TN-73', ['Kebili Governorate']],
  ['TN-41', ['Gouvernorat de Kairouan']],
  ['YE-AD', ['Aden Governorate', 'Adan Governorate', '\'Adan Governorate']],
  ['YE-AM', ["'Amran Governorate"]],
  ['YE-HJ', ['Hajjah Governorate']],
  ['YE-SN', ["Sana'a City", "Sana'a Governorate", "Sana'a"]],
  ['YE-LA', ['Lahij Governorate']],
  ['YE-TA', ["Ta'izz Governorate"]],
  ['YE-HD', ['Hadhramaut Governorate', 'Hadramaut Governorate']],
  ['YE-SU', ['Socotra Governorate']],
  ['YE-DH', ['Dhamar Governorate']],
  ['YE-MA', ["Ma'rib Governorate"]],
  ['MA-07', ['Marrakesh-Safi', 'مراكش - آسفي']],
  ['MA-09', ['Souss Massa', 'Souss-Massa']],
  ['MA-06', ['Grand Casablanca', 'Casablanca-Settat']],
  ['MA-04', ['Rabat-Salé-Kenitra', 'Rabat-Salé-Kénitra', 'جهة بني ملال خنيفرة']],
  ['MA-01', ['Tangier-Tétouan-Al Hoceima', 'Tanger-Tetouan-Al Hoceima', 'Tanger-Tétouan-Al Hoceima', 'فاس ـ بولمان']],
  ['MA-03', ['Fez-Meknès', 'Fès-Meknès']],
  ['MA-12', ['Western Sahara']],
  ['MA-05', ['Béni Mellal-Khenifra', 'Béni Mellal-Khénifra']],
  ['MA-02', ['Oriental', "L'Oriental"]],
  ['NP-P3', ['बागमती प्रदेश']],
  ['NP-P4', ['गण्डकी प्रदेश', 'Gandakī']],
  ['NP-P6', ['Karnālī', 'Setī']],
  ['NP-P1', ['Province No. 1', 'Sagamāthā', 'Mechī', 'Kosi Zone', 'कोशी प्रदेश']],
  ['NP-P5', ['लुम्बिनी प्रदेश', 'Lumbiniī']],
  ['NP-P2', ['Janakpur']],
  ['NP-P7', ['Nārāyanī']],
  ['SK-BC', ['Banská Bystrica Region', 'Banska Bystrica']],
  ['SK-BL', ['Bratislava Region', 'Bratislava']],
  ['SK-KI', ['Košice Region', 'Kosice']],
  ['SK-NI', ['Nitra Region']],
  ['SK-PV', ['Prešov Region', 'Presov']],
  ['SK-TC', ['Trenciansky', 'Trenčín Region']],
  ['SK-TA', ['Trnava Region']],
  ['SK-ZI', ['Žilina Region', 'Zilina']],
  ['UZ-AN', ['Andijan Region', 'Andijan region']],
  ['UZ-BU', ['Bukhara Region']],
  ['UZ-FA', ['Fergana Region', "Farg'ona Viloyati"]],
  ['UZ-JI', ['Jizzakh Region']],
  ['UZ-QA', ['Qashqadaryo Viloyati']],
  ['UZ-QR', ['Republic of Karakalpakstan', 'Qoraqalpoghiston']],
  ['UZ-SU', ['Surxondaryo Viloyati']],
  ['UZ-TO', ['Tashkent', 'Toshkent Viloyati', 'Tashkent Region']],
  ['UZ-TK', ['Toshkent Shahri']],
  ['UZ-XO', ['Xorazm Viloyati']],
  ['HN-FM', ['Departamento de Francisco Morazán', 'HNFM']],
  ['HN-IB', ['Bay Islands Department', 'HNIB']],
  ['HN-AT', ['Departamento de Atlántida', 'HNAT']],
  ['HN-CR', ['HNCR', 'Departamento de Cortés']],
  ['HN-CP', ['Departamento de Copán']],
  ['HN-YO', ['HNYR']],
  ['HN-LP', ['HNLP']],
  ['HN-OL', ['HNOL']],
  ['HN-CM', ['HNCM']],
  ['HN-EP', ['HNEP']],
  ['HN-CL', ['HNCT']],
  ['GR-A', ['Eastern Macedonia and Thrace']],
  ['GR-I', ['Attica']],
  ['GR-G', ['Western Greece']],
  ['GR-C', ['Western Macedonia']],
  ['GR-F', ['Ionian Islands']],
  ['GR-B', ['Central Macedonia', 'Thessaloniki']],
  ['GR-M', ['Crete']],
  ['GR-L', ['Southern Aegean']],
  ['GR-J', ['Peloponnese']],
  ['GR-H', ['Central Greece']],
  ['GR-E', ['Thessaly']],
  ['GR-K', ['Northern Aegean']],
  ['GR-69', ['Mount Athos']],
  ['GR-D', ['Epirus']],
  ['CO-CAQ', ['Caqueta']],
  ['CO-ATL', ['Atlantico']],
  ['CO-BOL', ['Bolivar']],
  ['CO-SAP', ['San Andrés and Providencia', 'San Andres and Providencia']],
  ['CO-BOY', ['Boyaca']],
  ['CO-COR', ['Cordoba']],
  ['CO-DC', ['Bogotá', 'Capital District', 'Bogota']],
  ['CO-NSA', ['North Santander']],
  ['CO-QUI', ['Quindio']],
  ['CO-NAR', ['Narino']],
  ['CO-CHO', ['Choco']],
  ['CO-GUA', ['Guainia']],
  ['CO-LAG', ['Louisiana']],
  ['MG-T', ['Analamanga', 'Itasy Region', 'Vakinankaratra']],
  ['MG-D', ['Diana', 'Sava', 'Sofia']],
  ['MG-F', ['Haute Matsiatra', 'Vatovavy-Fitovinany', "Amoron'i Mania"]],
  ['MG-M', ['Boeny', 'Menabe']],
  ['MG-A', ['Atsinanana', 'Bongolava']],
  ['MG-U', ['Atsimo-Andrefina', 'Anosy', 'Androy', 'Atsimo-Andrefana']],
  ['FR-PAC', ["Provence-Alpes-Côte d'Azur", 'PACA']],
  ['FR-BFC', ['Burgundy', 'Franche-Comté', 'FR-B9']],
  ['FR-ARA', ['Auvergne']],
  ['FR-NOR', ['Normandy', 'Upper Normandy']],
  ['FR-BRE', ['Brittany']],
  ['FR-PDL', ['Pays de la Loire']],
  ['FR-GES', ['Grand Est', 'Lorraine']],
  ['FR-CVL', ['Limousin']],
  ['FR-HDF', ['Nord-Pas-de-Calais', 'Picardy']],
  ['FR-NAQ', ['Aquitaine']],
  ['FR-20R', ['Corsica']],
  ['JO-AM', ['Amman', 'Amman Governorate', 'Al ‘A̅şimah', 'محافظة العاصمة']],
  ['JO-AZ', ['Zarqa', 'Zarqa Governorate', 'Az Zarqā’']],
  ['JO-BA', ['Balqa', 'Balqa Governorate', 'Al Balqā’']],
  ['JO-KA', ['Karak', 'Karak Governorate', 'Al Karak']],
  ['JO-MA', ['Mafraq', 'Mafraq Governorate', 'Al Mafraq']],
  ['JO-AQ', ['Al ‘Aqabah']],
  ['JO-AT', ['Tafilah Governorate', 'Aţ Ţafīlah']],
  ['JO-IR', ['Irbid']],
  ['JO-JA', ['Jerash', 'Jarash', 'Jerash Governorate']],
  ['JO-MN', ['Maan', "Ma'an Governorate", 'Ma‘ān']],
  ['JO-MD', ['Madaba', 'Madaba Governorate', 'Mādabā']],
  ['JO-AJ', ['Ajloun Governorate', '‘Ajlūn']],
  ['DZ-16', ['Algiers Province', "Wilaya d'Alger", 'Algiers', 'Algeria']],
  ['DZ-34', ['Bordj Bou Arreridj']],
  ['DZ-08', ['Bashar']],
  ['DZ-52', ['Beni Abbes']],
  ['DZ-06', ['Bejaia', 'Wilaya de Béjaïa']],
  ['DZ-36', ['El Taref Province']],
  ['DZ-10', ['Bouïra Province']],
  ['DZ-35', ['Boumerdes']],
  ['DZ-47', ['Ghardaia', 'Ghardaia Province']],
  ['DZ-19', ['Setif']],
  ['DZ-31', ['ولاية وهران']],
  ['DZ-45', ['Naâma Province']],
  ['DZ-57', ["El M'Ghair"]],
  ['LT-AL', ['Alytus County', 'Alytaus']],
  ['LT-KL', ['Klaipėdos', 'Klaipėda County']],
  ['LT-TE', ['Telšiai County']],
  ['LT-TA', ['Tauragė County']],
  ['LT-VL', ['Vilnius Region', 'Vilnius County', 'Vilniaus']],
  ['LT-KU', ['Kauno m.', 'Kaunas Region', 'Kauno', 'Kaunas County']],
  ['LT-MR', ['Marijampolė County']],
  ['LT-PN', ['Panevėžio', 'Panevėžys County']],
  ['LT-SA', ['Šiauliai County']],
  ['LT-UT', ['Utena County']],
  ['AF-NAN', ['Nangarhar Province', 'Nangarhar']],
  ['AF-ZAB', ['Zabul']],
  ['AF-GHO', ['Ghor', 'Ghor Province']],
  ['AF-PAR', ['Parwan']],
  ['AF-KNR', ['Kunar']],
  ['AF-GHA', ['Ghazni Province', 'Ghazni']],
  ['AF-HER', ['Herat', 'Herat Province']],
  ['AF-BGL', ['Baghlan Province']],
  ['AF-KAN', ['Kandahar']],
  ['AF-BDG', ['Badghis']],
  ['AF-KAB', ['Kabul', 'Kabul Province']],
  ['AF-TAK', ['Takhar']],
  ['AF-KHO', ['Khost']],
  ['AF-JOW', ['Jowzjan']],
  ['MX-AGU', ['AGS']],
  ['MX-NLE', ['Nuevo Leon', 'NL']],
  ['MX-MIC', ['MICH']],
  ['MX-TLA', ['TLAX']],
  ['MX-HID', ['HGO']],
  ['MX-QUE', ['QRO']],
  ['MX-TAM', ['TAMPS']],
  ['MX-MEX', ['Estado de México', 'State of Mexico']],
  ['MX-CHP', ['CHIS']],
  ['MX-DUR', ['DGO']],
  ['MX-SLP', ['San Luis Potosi']],
  ['MX-CHH', ['CHIH']],
  ['MX-COA', ['COAH']],
  ['MX-CMX', ['CDMX', 'Mexico City']],
  ['MX-GUA', ['GTO']],
  ['MX-YUC', ['Yucatan']],
  ['MX-ROO', ['QR']],
  ['LY-ZA', ['Az Zawiya District', 'Zawiya District', 'Sabratha Wa Surman']],
  ['LY-SB', ['Sabha District']],
  ['LY-WA', ['Al Wahat', 'Al Wahat District']],
  ['LY-BA', ['Benghazi', 'Benghazi district']],
  ['LY-NQ', ['Nuqat al Khams District', 'Bani Walid']],
  ['LY-BU', ['Butnan District']],
  ['LY-WD', ['Wadi al Hayaa District']],
  ['LY-JA', ['Jabal al Akhdar District']],
  ['LY-JG', ['Jabal al Gharbi', 'Jabal al Gharbi District']],
  ['LY-MQ', ['Murzuq District']],
  ['LY-WS', ['Wadi al Shatii']],
  ['LY-TB', ['Tripoli', 'Tripoli District']],
  ['LY-MI', ['Misrata District']],
  ['LY-GT', ['Gharyan']],
  ['SE-K', ['Blekinge County']],
  ['SE-W', ['Dalarna County']],
  ['SE-I', ['Gotland County']],
  ['SE-X', ['Gävleborg County', 'Gavleborg County']],
  ['SE-N', ['Halland County']],
  ['SE-Z', ['Jamtland County', 'Jämtlands län']],
  ['SE-F', ['Jonkoping County', 'Jönköpings län']],
  ['SE-H', ['Kalmar County']],
  ['SE-G', ['Kronoberg County']],
  ['SE-BD', ['Norrbotten County']],
  ['SE-M', ['Skåne County']],
  ['SE-AB', ['Stockholm County']],
  ['SE-D', ['Södermanland County']],
  ['SE-C', ['Uppsala County']],
  ['SE-S', ['Varmland County', 'Värmlands län']],
  ['SE-AC', ['Västerbotten County']],
  ['SE-Y', ['Västernorrland County']],
  ['SE-U', ['Västmanland County']],
  ['SE-O', ['Västra Götaland County', 'Västra Götalands län']],
  ['SE-T', ['Örebro County']],
  ['SE-E', ['Östergötland County']],
  ['CZ-20', ['Central Bohemian Region', 'Central Bohemia']],
  ['CZ-64', ['South Moravian Region', 'South Moravia']],
  ['CZ-80', ['Moravian-Silesian Region', 'Moravia-Silesia']],
  ['CZ-41', ['Karlovy Vary Region']],
  ['CZ-42', ['Ústí nad Labem Region']],
  ['CZ-53', ['Pardubice Region']],
  ['CZ-32', ['Plzeň Region', 'Plzeň']],
  ['CZ-63', ['Vysočina Region', 'Vysočina']],
  ['CZ-52', ['Hradec Králové Region']],
  ['CZ-51', ['Liberec Region']],
  ['CZ-71', ['Olomouc Region']],
  ['CZ-31', ['South Bohemian Region', 'South Bohemia']],
  ['CZ-72', ['Zlin', 'Zlín Region']],
  ['CZ-10', ['Prague', 'Hlavní město Praha']],
  ['EE-45', ['Ida-Viru County']],
  ['EE-37', ['Harju', 'Harju County', 'Harju maakond']],
  ['EE-87', ['Võru County']],
  ['EE-79', ['Tartu maakond', 'Tartu County']],
  ['EE-56', ['Lääne County', 'Laane']],
  ['EE-60', ['Lääne-Viru County', 'Lääne-Viru maakond', 'Laane-Viru']],
  ['EE-39', ['Hiiumaa']],
  ['EE-68', ['Pärnu maakond', 'Pärnu County', 'Parnu']],
  ['EE-52', ['Järvamaa']],
  ['EE-50', ['Jõgeva County']],
  ['EE-64', ['Põlvamaa']],
  ['EE-71', ['Raplamaa', 'Rapla County']],
  ['EE-74', ['Saaremaa', 'Saare County']],
  ['EE-84', ['Viljandimaa', 'Viljandi maakond', 'Viljandi County']],
  ['EE-81', ['Valgamaa', 'Valga County', 'Valga maakond']],
  ['ES-GA', ['Galicia']],
  ['ES-VC', ['Comunitat Valenciana', 'Valencian Community', 'Comunidad Valenciana']],
  ['ES-CM', ['Castilla-La Mancha', 'Castile-La Mancha']],
  ['ES-AN', ['Andalucía', 'Andalusia']],
  ['ES-PV', ['País Vasco', 'Euskadi', 'Basque Country']],
  ['ES-AR', ['Aragón', 'Aragon']],
  ['ES-AS', ['Asturias', 'Principality of Asturias', 'Principado de Asturias']],
  ['ES-EX', ['Extremadura']],
  ['ES-CT', ['Catalunya', 'Catalonia', 'Cataluña']],
  ['ES-CL', ['Castilla y León', 'Castile and León', 'Castilla and Leon']],
  ['ES-CN', ['Canarias', 'Canary Islands']],
  ['ES-CB', ['Cantabria']],
  ['ES-CE', ['Ceuta']],
  ['ES-IB', ['Illes Balears', 'Islas Baleares', 'Balearic Islands']],
  ['ES-RI', ['La Rioja', 'Autonomía de La Rioja', 'Autonomía de La Rioja']],
  ['ES-MD', ['Madrid', 'Community of Madrid', 'Comunidad de Madrid']],
  ['ES-ML', ['Melilla']],
  ['ES-MC', ['Murcia', 'Región de Murcia', 'Region of Murcia']],
  ['ES-NC', ['Navarra', 'Chartered Community of Navarre', 'Navarre']],
  ['CL-AI', ['Aysén', 'XII', 'XI']],
  ['CL-AN', ['Antofagasta', 'II']],
  ['CL-AP', ['Arica y Parinacota', 'XV']],
  ['CL-AT', ['Atacama', 'III']],
  ['CL-BI', ['Biobío', 'Bío Bío', 'VIII', 'Bio Bio']],
  ['CL-CO', ['Coquimbo', 'IV']],
  ['CL-AR', ['La Araucanía', 'IX', 'Araucania', 'Araucanía']],
  ['CL-LI', ["Libertador General Bernardo O'Higgins", 'VI']],
  ['CL-LL', ['Los Lagos', 'X']],
  ['CL-LR', ['Los Ríos', 'XIV']],
  ['CL-MA', ['Magallanes', 'Magallanes y la Antártica Chilena', 'Magallanes and Chilean Antarctica', 'I']],
  ['CL-ML', ['Maule', 'VII']],
  ['CL-RM', ['Región Metropolitana de Santiago', 'Santiago Metropolitan Region', 'Región Metropolitana', 'XVI']],
  ['CL-TA', ['Tarapacá', 'I']],
  ['CL-VS', ['Valparaíso', 'Valparaiso Region', 'V']],
  ['CL-NB', ['Ñuble', 'XVI']],
  ['BG-01', ['Blagoevgrad Province']],
  ['BG-03', ['Varna Province']],
  ['BG-04', ['Veliko Tarnovo Province', 'Veliko Turnovo']],
  ['BG-05', ['Vidin Province']],
  ['BG-06', ['Vratsa Province']],
  ['BG-07', ['Gabrovo Province']],
  ['BG-08', ['Dobrich Province']],
  ['BG-09', ['Kardzhali Province']],
  ['BG-10', ['Kyustendil Province']],
  ['BG-11', ['Lovech Province', 'Lovec']],
  ['BG-12', ['Montana Province']],
  ['BG-13', ['Pazardzhik Province']],
  ['BG-14', ['Pernik Province']],
  ['BG-15', ['Pleven Province']],
  ['BG-16', ['Plovdiv Province']],
  ['BG-17', ['Razgrad Province']],
  ['BG-18', ['Ruse Province']],
  ['BG-19', ['Silistra Province']],
  ['BG-20', ['Sliven Province']],
  ['BG-21', ['Smolyan Province', 'Smoljan']],
  ['BG-22', ['Sofia City', 'Sofia City Province', 'Sofia-Grad']],
  ['BG-23', ['Sofia Province', 'Sofiyska oblast']],
  ['BG-24', ['Stara Zagora Province']],
  ['BG-25', ['Targovishte Province', 'Turgovishte']],
  ['BG-26', ['Haskovo Province', 'Khaskovo', 'Хасково']],
  ['BG-27', ['Shumen Province']],
  ['BG-28', ['Yambol Province', 'Jambol']],
  ['AR-B', ['Provincia de Buenos Aires', 'BA']],
  ['AR-K', ['CTM']],
  ['AR-H', ['CHB']],
  ['AR-U', ['RN']],
  ['AR-C', ['CBA', 'Buenos Aires Autonomous City']],
  ['AR-W', ['CRR']],
  ['AR-X', ['CCO']],
  ['AR-E', ['ER']],
  ['AR-P', ['FSA']],
  ['AR-Y', ['JJY']],
  ['AR-L', ['LP']],
  ['AR-F', ['LR']],
  ['AR-M', ['MZA']],
  ['AR-N', ['MIS']],
  ['AR-Q', ['NQN']],
  ['AR-R', ['RIO NEGRO', 'RN']],
  ['AR-A', ['SA']],
  ['AR-J', ['SJ']],
  ['AR-D', ['SL']],
  ['AR-Z', ['SC']],
  ['AR-S', ['SF']],
  ['AR-G', ['SDE']],
  ['AR-V', ['TDF']],
  ['AR-T', ['TU', 'CA']],
  [
    'IE-M',
    [
      'County Kerry',
      'County Cork',
      'County Limerick',
      'County Tipperary',
      'County Waterford',
      'County Clare'
    ]
  ],
  ['IE-U', ['County Donegal', 'County Monaghan', 'County Cavan']],
  [
    'IE-C',
    [
      'County Galway',
      'County Mayo',
      'County Roscommon',
      'County Leitrim',
      'County Sligo'
    ]
  ],
  [
    'IE-L',
    [
      'County Meath',
      'County Dublin',
      'County Laois',
      'County Kildare',
      'County Wicklow',
      'County Westmeath',
      'County Longford',
      'County Offaly',
      'County Louth',
      'County Carlow',
      'County Wexford',
      'County Kilkenny'
    ]
  ],
  ['KZ-10', ['Abay Region', 'Abai Region']],
  ['KZ-11', ['Akmola Region', 'Aqmola oblısı']],
  ['KZ-15', ['Aktobe Region', 'Aqtöbe region']],
  ['KZ-19', ['Almaty Region', 'Алматы облысы', 'Almatı oblısı']],
  ['KZ-75', ['Almaty', 'Алматы']],
  ['KZ-71', ['Astana']],
  ['KZ-23', ['Atyrau Region']],
  ['KZ-27', ['West Kazakhstan Region', "Zapadno-Kazakhstanskaya oblast'"]],
  ['KZ-35', ['Karaganda Region', 'Qarağandı oblısı']],
  ['KZ-39', ['Kostanay Region']],
  ['KZ-43', ['Kyzylorda Region', 'Қызылорда облысы']],
  ['KZ-47', ['Mangystau Region']],
  ['KZ-55', ['Pavlodar Region', 'Pavlodar oblısı']],
  ['KZ-59', ['North Kazakhstan Region']],
  ['KZ-63', ['East Kazakhstan Region']],
  ['KZ-79', ['Шimkent']],
  ['KZ-61', ['Turkistan Region', "Turkestanskaja oblast'"]],
  ['KZ-62', ['Ulytau Region']],
  ['KZ-31', ['Жамбыл облысы', 'Jambyl Region']],
  ['KZ-33', ['Jetisu Region', 'Жetysuskaja oblast’']],
  ['BR-RO', ['State of Rondônia']],
  ['BR-PE', ['State of Pernambuco']],
  ['BR-AC', ['State of Acre']],
  ['BR-MS', ['State of Mato Grosso do Sul']],
  ['BR-SE', ['State of Sergipe']],
  ['BR-RJ', ['State of Rio de Janeiro']],
  ['BR-RS', ['State of Rio Grande do Sul']],
  ['BR-AL', ['State of Alagoas']],
  ['BR-GO', ['State of Goiás']],
  ['BR-TO', ['State of Tocantins']],
  ['BR-AP', ['State of Amapá']],
  ['BR-MT', ['State of Mato Grosso']],
  ['BR-SP', ['State of São Paulo']],
  ['BR-DF', ['Federal District']],
  ['BR-ES', ['State of Espírito Santo']],
  ['BR-RN', ['State of Rio Grande do Norte']],
  ['BR-SC', ['State of Santa Catarina']],
  ['BR-RR', ['State of Roraima']],
  ['BR-AM', ['State of Amazonas']],
  ['BR-PI', ['State of Piauí']],
  ['BR-PA', ['State of Pará']],
  ['BR-MA', ['State of Maranhão']],
  ['BR-PR', ['State of Paraná']],
  ['BR-MG', ['State of Minas Gerais']],
  ['BR-BA', ['State of Bahia']],
  ['BR-CE', ['State of Ceará']],
  ['BR-PB', ['State of Paraíba']],
  ['VE-Z', ['Amazonas']],
  ['VE-B', ['Anzoategui', 'AN']],
  ['VE-C', ['Apure', 'AP']],
  ['VE-D', ['Aragua', 'AR']],
  ['VE-E', ['Barinas', 'BA']],
  ['VE-F', ['Bolívar', 'BO']],
  ['VE-G', ['Carabobo', 'CA']],
  ['VE-H', ['Cojedes', 'CO']],
  ['VE-Y', ['Delta Amacuro']],
  ['VE-W', ['Dependencias Federales', 'Federal District', 'DC']],
  ['VE-A', ['Distrito Capital', 'Capital District', 'VA']],
  ['VE-I', ['Falcón', 'FA']],
  ['VE-J', ['Guárico', 'GU']],
  ['VE-X', ['La Guaira', 'LA', 'Vargas']],
  ['VE-K', ['Lara', 'TA']],
  ['VE-M', ['Miranda', 'MI']],
  ['VE-N', ['Monagas', 'MO']],
  ['VE-L', ['Mérida', 'ME']],
  ['VE-O', ['Nueva Esparta', 'NE']],
  ['VE-P', ['Portuguesa', 'PO']],
  ['VE-R', ['Sucre', 'SU']],
  ['VE-T', ['Trujillo', 'TR']],
  ['VE-S', ['Táchira', 'Tachira State']],
  ['VE-U', ['Yaracuy', 'YA']],
  ['VE-V', ['Zulia', 'ZU']],
  ['SA-14', ['ASR', 'Aseer Province']],
  ['SA-11', ['EAS', 'Al Bahah Province']],
  ['SA-12', ['JOF', 'Al Jowf Province', 'Al Jawf Province']],
  ['SA-03', ['MAM', 'Al Madinah Province', 'Al Madīnah al Munawwarah']],
  ['SA-05', ['ALT', 'Al Qassim Province', 'Al Qaşīm', 'QAS']],
  ['SA-08', ['NAR', 'Northern Borders Province', 'Al Ḩudūd ash Shamālīyah']],
  ['SA-01', ['RIY', 'Riyadh', 'Ar Riyāḑ', 'Riyadh Province']],
  ['SA-04', ['EAS', 'Eastern', 'Eastern Province', 'Ash Sharqīyah']],
  ['SA-09', ['JAZ', 'Jazan Province', 'Jāzān']],
  ['SA-02', ['Makkah', 'Makkah Province', 'Makkah al Mukarramah']],
  ['SA-10', ['NAR', 'Najran Province', 'Najrān']],
  ['SA-07', ['TAB', 'Tabuk Province', 'Tabūk']],
  ['SA-06', ['HAI', 'Hail Province', "⚗ā'il"]],
  ['IQ-AN', ['Al Anbar Governorate', 'Al-Anbar Governorate']],
  ['IQ-BA', ['Basra Governorate', 'Al-Basra Governorate']],
  ['IQ-MU', ['Al Muthanna Governorate']],
  ['IQ-QA', ['Al-Qādisiyyah Governorate']],
  ['IQ-NA', ['Al-Najaf Governorate', 'Najaf Governorate']],
  ['IQ-BG', ['Baghdad Governorate', 'بغداد محافظة']],
  ['IQ-BB', ['Babylon Governorate', 'Babil Governorate']],
  ['IQ-DQ', ['Dhi Qar Governorate']],
  ['IQ-DI', ['Diyala Governorate']],
  ['IQ-KA', ['Karbala', 'Karbala Governorate', 'كربلاء محافظة']],
  ['IQ-KI', ['Kirkuk Governorate']],
  ['IQ-MA', ['Maysan Governorate']],
  ['IQ-NI', ['Nineveh Governorate']],
  ['IQ-WA', ['Wasit Governorate']],
  ['IQ-SD', ['Saladin Governorate', 'صلاح الدين محافظة']],
  ['IQ-KR', ['Kurdistan Region', 'Kurdistan', 'Erbil Governorate', 'أربيل محافظة', 'Duhok Governorate', 'Sulaymaniyah Governorate']],
  ['ID-JW', ['Central Java', 'East Java', 'West Java', 'Special Region of Yogyakarta', 'Daerah Istimewa Yogyakarta',
    'Daerah Khusus Ibukota Jakarta', 'Jakarta']],
  ['ID-SM', ['South Sumatra', 'West Sumatra', 'North Sumatra', 'Bangka-Belitung', 'Bangka Belitung Islands', 'Riau Islands']],
  ['ID-NU', ['West Nusa Tenggara', 'East Nusa Tenggara']],
  [
    'ID-SL',
    [
      'Central Sulawesi',
      'West Sulawesi',
      'South East Sulawesi',
      'North Sulawesi',
      'South Sulawesi',
      'Southeast Sulawesi'
    ]
  ],
  [
    'ID-KA',
    [
      'Central Kalimantan',
      'West Kalimantan',
      'South Kalimantan',
      'East Kalimantan',
      'North Kalimantan'
    ]
  ],
  ['ID-ML', ['North Maluku', 'Maluku']],
  ['ID-PP', ['West Papua', 'Papua']],
  ['ID-JK', ['Daerah Khusus Ibukota Jakarta', 'Jakarta']],
  [
    'ID-YO',
    ['Special Region of Yogyakarta', 'Daerah Istimewa Yogyakarta']
  ],
  ['ID-RI', ['Riau Islands']],
  ['IT-34', ['Ven.', 'Veneto']],
  ['IT-72', ['Camp.', 'Campania']],
  ['IT-23', ['Aosta', 'V.d.A.', 'Aosta Valley', "Valle d'Aosta"]],
  ['IT-55', ['Umbr.', 'Umbria']],
  ['IT-25', ['Lombardy', 'Lomb.', 'Lombardia']],
  ['IT-62', ['Laz.', 'Latium', 'Lazio']],
  [
    'IT-32',
    ['Trentino-South Tyrol', 'Tr.A.A.', 'Trentino-Südtirol']
  ],
  ['IT-65', ['Abr.', 'Abruzzo']],
  ['IT-67', ['Mol.', 'Molise']],
  ['IT-82', ['Sic.', 'Sicily', 'Sicilia']],
  ['IT-21', ['Piem.', 'Piedmont', 'Piemonte']],
  ['IT-45', ['Em.Rom.', 'Emilia-Romagna']],
  ['IT-42', ['Lig.', 'Liguria']],
  ['IT-57', ['Marc.', 'Marches', 'Marche']],
  ['IT-88', ['Sardinia', 'Sard.', 'Sardegna']],
  ['IT-78', ['Cal.', 'Calabria']],
  ['IT-52', ['Tuscany', 'Tosc.', 'Toscana']],
  ['IT-75', ['Apulia', 'Pugl.', 'Puglia']],
  ['IT-77', ['Bas.', 'Basilicata']],
  ['IT-36', ['Friuli-Venezia Giulia', 'Fr.V.G.']],
  ['FI-01', ['Landskapet Åland']],
  ['FI-02', ['South Karelia']],
  ['FI-03', ['South Ostrobothnia', 'FI131', 'FI132', 'FI133', 'FI134']],
  ['FI-04', ['South Savo']],
  ['FI-05', ['Kajanaland']],
  ['FI-06', ['Egentliga Tavastland']],
  ['FI-07', ['Central Ostrobothnia', 'FI1A1']],
  ['FI-08', ['Central Finland']],
  ['FI-09', ['Kymmenedalen']],
  ['FI-10', ['Lappland', 'Lapland', 'FI1A3']],
  ['FI-11', ['Birkaland']],
  ['FI-12', ['Ostrobothnia']],
  ['FI-13', ['North Karelia']],
  ['FI-14', ['North Ostrobothnia', 'Northern Ostrobothnia', 'FI1A2']],
  ['FI-15', ['North Savo']],
  ['FI-16', ['Päijänne Tavastia', 'Päijänne-Tavastland']],
  ['FI-17', ['Satakunta']],
  ['FI-18', ['Nyland', 'Southwest Finland', 'FI181', 'FI182', 'FI183', 'FI184', 'FI185', 'FI186', 'FI187']],
  ['FI-19', ['Egentliga Finland', 'Tavastia Proper', 'FI193', 'FI194', 'FI195', 'FI196', 'FI197']],
  ['IR-30', ['Alborz']],
  ['IR-24', ['Ardabil Province', 'استان اردبیل']],
  ['IR-18', ['Bushehr Province', 'Būshehr']],
  ['IR-14', ['Chahār Maḩāl va Bakhtīārī', 'Chaharmahal and Bakhtiari Province']],
  ['IR-10', ['Eşfahān', 'Isfahan Province']],
  ['IR-07', ['Fārs', 'Fars Province']],
  ['IR-27', ['Golestān', 'Golestan Province']],
  ['IR-01', ['Gīlān', 'Gilan Province']],
  ['IR-13', ['Hamadān', 'Hamadan Province']],
  ['IR-22', ['Hormozgān', 'Hormozgan Province']],
  ['IR-08', ['Kermān', 'Kerman Province']],
  ['IR-05', ['Kermānshāh', 'Kermanshah Province']],
  ['IR-29', ['Khorāsān-e Jonūbī', 'South Khorasan Province']],
  [
    'IR-09',
    ['Khorāsān-e Raẕavī', 'Razavi Khorasan',
      'خراسان رضوی', 'Razavi Khorasan Province', 'استان خراسان رضوی']
  ],
  ['IR-28', ['Khorāsān-e Shomālī', 'North Khorasan Province']],
  ['IR-06', ['Khūzestān', 'Khuzestan Province']],
  [
    'IR-17',
    [
      'Kohgīlūyeh va Bowyer Aḩmad',
      'Kohgiluyeh and Boyer-Ahmad Province'
    ]
  ],
  ['IR-12', ['Kordestān', 'Kurdistan Province']],
  ['IR-15', ['Lorestān', 'Lorestan Province']],
  ['IR-00', ['Markazī', 'Markazi Province']],
  ['IR-02', ['Māzandarān', 'Mazandaran Province']],
  ['IR-26', ['Qazvīn', 'Qazvin Province']],
  ['IR-25', ['Qom']],
  ['IR-20', ['Semnān', 'Semnan Province']],
  ['IR-11', ['Sīstān va Balūchestān', 'Sistan and Baluchestan Province']],
  ['IR-23', ['Tehrān', 'Tehran Province']],
  ['IR-21', ['Yazd', 'استان یزد']],
  ['IR-19', ['Zanjān', 'Zanjan Province']],
  ['IR-04', ['Āz̄ārbāyjān-e Ghārbī', 'West Azerbaijan Province']],
  ['IR-03', ['Āz̄ārbāyjān-e Shārqī', 'East Azerbaijan Province']],
  ['IR-16', ['Īlām', 'Ilam Province']],
  ['MK-604', ['Municipality of Gostivar']],
  ['MK-405', ['Municipality of Gevgelija']],
  ['MK-102', ['Municipality of Gradsko']],
  ['MK-312', ['Municipality of Struga', 'Southwestern']],
  ['MK-409', ['Municipality of Radoviš']],
  ['MK-703', ['Municipality of Kumanovo', 'Northeastern']],
  ['MK-101', ['Municipality of Veles']],
  ['MK-104', ['Municipality of Kavadarci']],
  ['MK-701', ['Municipality of Kratovo']],
  ['MK-508', ['Municipality of Prilep']],
  ['MK-502', ['Municipality of Demir Hisar']],
  ['MK-310', ['Municipality of Ohrid']],
  ['MK-108', ['Municipality of Sveti Nikole']],
  ['MK-505', ['Municipality of Kruševo']],
  ['MK-609', ['Municipality of Tetovo', 'Општина Тетово']],
  ['MK-106', ['Municipality of Negotino']],
  ['MK-211', ['Municipality of Štip']],
  ['MK-403', ['Municipality of Valandovo']],
  ['MK-501', ['Municipality of Bitola', 'Pelagonia']],
  ['MK-201', ['Municipality of Berovo']],
  ['MK-202', ['Municipality of Vinica']],
  ['MK-605', ['Municipality of Želino']],
  ['MK-609', ['Municipality of Tetovo', 'Polog', 'Општина Тетово']],
  ['MK-303', ['Municipality of Debar']],
  ['MK-410', ['Municipality of Strumitsa', 'Southeastern']],
  ['MK-406', ['Municipality of Dojran']],
  ['MK-203', ['Municipality of Delcevo']],
  ['MK-407', ['Municipality of Konče']],
  ['MK-208', ['Municipality of Pehčevo']],
  ['MK-509', ['Municipality of Resen']],
  ['MK-206', ['Municipality of Kočani', 'Eastern']],
  ['MK-401', ['Municipality of Bogdanci']],
  ['MK-601', ['Municipality of Bogovinje']],
  ['MK-402', ['Municipality of Bosilovo']],
  ['MK-602', ['Municipality of Brvenica']],
  ['MK-801', ['Aerodrom', 'Vardar', 'Greater Skopje', 'Skopje Statistical Region']],
  ['MK-802', ['Aračinovo']],
  ['MK-803', ['Butel']],
  ['MK-804', ['Gazi Baba']],
  ['MK-805', ['Gjorče Petrov']],
  ['MK-806', ['Zelenikovo']],
  ['MK-807', ['Ilinden']],
  ['MK-808', ['Karpoš']],
  ['MK-809', ['Kisela Voda']],
  ['MK-810', ['Petrovec']],
  ['MK-811', ['Saraj']],
  ['MK-812', ['Sopište']],
  ['MK-813', ['Studeničani']],
  ['MK-814', ['Centar']],
  ['MK-815', ['Čair']],
  ['MK-816', ['Čučer-Sandevo']],
  ['MK-817', ['Šuto Orizari']],
  ['HR-07', ['Bjelovar-Bilogora County', 'Bjelovar-Bilogora']],
  ['HR-12', ['Brod-Posavina County', 'Brod-Posavina']],
  ['HR-19', ['Dubrovnik-Neretva County', 'Dubrovnik-Neretva']],
  ['HR-21', ['City of Zagreb', 'Zagreb']],
  ['HR-18', ['Istria', 'Istria County']],
  ['HR-04', ['County of Karlovac', 'Karlovac County', 'Karlovac']],
  ['HR-06', ['Koprivnicko-Krizevacka', 'Koprivnica-Križevci County']],
  ['HR-02', ['Krapina-Zagorje', 'Krapina-Zagorje County']],
  ['HR-09', ['Lika-Senj County']],
  ['HR-20', ['Međimurje', 'Međimurje County']],
  ['HR-14', ['Osijek-Baranja', 'Osijek-Baranja County']],
  ['HR-11', ['Požega-Slavonia', 'Požeško-slavonska županija', 'Požega-Slavonia County']],
  ['HR-08', ['Primorje-Gorski', 'Primorje-Gorski Kotar County']],
  [
    'HR-03',
    [
      'Sisak-Moslavina',
      'Sisačko-moslavačka županija',
      'Sisak-Moslavina County'
    ]
  ],
  ['HR-17', ['Split-Dalmatia', 'Split-Dalmatia County']],
  ['HR-05', ['Varaždin', 'Varaždinska županija', 'Varaždin County']],
  ['HR-10', ['Virovitica-Podravina', 'Virovitica-Podravina County']],
  [
    'HR-16',
    [
      'Vukovar-Srijem',
      'Vukovarsko-srijemska županija',
      'Vukovar-Srijem County'
    ]
  ],
  ['HR-13', ['Zadar', 'Zadarska županija', 'Zadar County']],
  ['HR-01', ['Zagreb County']],
  ['HR-15', ['Šibenik-Knin County']],
  ['TH-86', ['Chang Wat Phang-nga', 'Phang-nga', 'Phang Nga', 'จ.​ชุมพร']],
  ['TH-33', ['Sisaket']],
  ['TH-16', ['Lopburi', 'Chang Wat Lopburi']],
  ['TH-41', ['Chang Wat Udon Thani']],
  ['TH-44', ['Chang Wat Maha Sarakham']],
  ['TH-10', ['กรุงเทพมหานคร', 'Bangkok City']],
  ['TH-57', ['Chang Wat Chiang Rai']],
  ['TH-72', ['Chang Wat Suphan Buri']],
  ['TH-12', ['Chang Wat Nonthaburi']],
  ['TH-48', ['Chang Wat Nakhon Phanom']],
  ['TH-96', ['Chang Wat Narathiwat']],
  ['TH-11', ['Chang Wat Samut Prakan']],
  ['TH-30', ['Chang Wat Nakhon Ratchasima', 'นครราชสีมา']],
  ['TH-73', ['Chang Wat Nakhon Pathom']],
  ['TH-31', ['Chang Wat Buri Ram']],
  ['TH-56', ['Chang Wat Phayao']],
  ['TH-20', ['ชลบุรี', 'Chang Wat Chon Buri']],
  ['TH-90', ['Chang Wat Songkhla']],
  ['TH-40', ['Chang Wat Khon Kaen']],
  ['TH-34', ['Chang Wat Ubon Ratchathani']],
  ['TH-83', ['Chang Wat Phuket']],
  ['TH-47', ['Chang Wat Sakon Nakhon']],
  ['TH-19', ['Sara Buri', 'Saraburi']],
  ['TH-51', ['Chang Wat Lamphun', 'ลำพูน']],
  ['TH-50', ['Chang Wat Chiang Mai']],
  ['TH-21', ['Chang Wat Rayong']],
  ['TH-13', ['Chang Wat Pathum Thani']],
  ['TH-32', ['Chang Wat Surin']],
  ['TH-18', ['Chang Wat Chai Nat']],
  ['TH-25', ['Chang Wat Prachin Buri']],
  ['TH-36', ['Chang Wat Chaiyaphum']],
  ['TH-66', ['Chang Wat Phichit']],
  ['TH-52', ['ลำปาง']],
  ['EG-DK', ['Dakahlia Governorate', 'El Daqahlia', 'Ad Daqahliyah']],
  ['EG-BA', ['Al Bahr al Ahmar']],
  ['EG-BH', ['Al Buḩayrah', 'Beheira Governorate', 'Al Buhayrah']],
  ['EG-FYM', ['Al Fayyūm', 'Faiyum Governorate', 'Al Fayyum']],
  [
    'EG-GH',
    [
      'Al Gharbīyah',
      'Gharbia Governorate',
      'Al Gharbiyah',
      'محافظة الغربية'
    ]
  ],
  ['EG-ALX', ['Alexandria', 'محافظة الإسكندرية']],
  ['EG-IS', ["Al Ismā'īlīyah", 'Ismailia Governorate', "Al Isma'iliyah"]],
  ['EG-GZ', ['Al Jīzah', 'Al Jizah', 'محافظة الجيزة']],
  ['EG-MN', ['Al Minyā', 'Minya Governorate', 'Al Minya']],
  ['EG-MNF', ['Al Minūfīyah', 'Menofia Governorate', 'Al Minufiyah']],
  [
    'EG-KB',
    [
      'Al Qalyūbīyah',
      'Al Qalyubia Governorate',
      'Al Qalyubiyah',
      'Al-Qalyubia Governorate'
    ]
  ],
  ['EG-C', ['Al Qāhirah', 'Cairo', 'محافظة القاهرة‬']],
  ['EG-LX', ['Al Uqşur']],
  ['EG-WAD', ['Al Wādī al Jadīd', 'The New Valley Governorate']],
  ['EG-SUZ', ['As Suways', 'Suez', 'محافظة السويس']],
  [
    'EG-SHR',
    [
      'Ash Sharqīyah',
      'Ash Sharqia Governorate',
      'Al-Sharqia Governorate',
      'Sharkia'
    ]
  ],
  ['EG-ASN', ['Aswān', 'Aswan Governorate', 'Aswan']],
  ['EG-AST', ['Asyūţ', 'Assiut Governorate', 'Asyut']],
  ['EG-BNS', ['Banī Suwayf', 'Bani Suwayf', 'Beni Suef Governorate']],
  ['EG-PTS', ['Būr Sa‘īd', "Bur Sa'id"]],
  ['EG-DT', ['Dumyāţ', 'Dumyat']],
  ['EG-JS', ["Janūb Sīnā'", 'South Sinai']],
  ['EG-KFS', ['Kafr ash Shaykh', 'Kafr El-Sheikh Governorate']],
  ['EG-MT', ['Maţrūḩ', 'Marsa Matrouh Governorate']],
  ['EG-KN', ['Qinā', 'Qena Governorate', 'Qina']],
  ['EG-SIN', ["Shamāl Sīnā'", 'North Sinai']],
  ['EG-SHG', ['Sūhāj', 'Suhaj']],
  ['PL-02', ['Lower Silesian Voivodeship', 'Województwo dolnośląskie', 'DS']],
  ['PL-04', ['Kuyavian-Pomeranian Voivodeship', 'Województwo kujawsko-pomorskie', 'KP']],
  ['PL-06', ['Lublin Voivodeship', 'Województwo lubelskie', 'LU']],
  ['PL-08', ['Lubusz Voivodeship', 'Województwo lubuskie', 'LB']],
  ['PL-14', ['Masovian Voivodeship', 'Województwo mazowieckie', 'MZ']],
  ['PL-12', ['Lesser Poland Voivodeship', 'Województwo małopolskie', 'MA']],
  ['PL-16', ['Opole Voivodeship', 'Województwo opolskie', 'OP']],
  ['PL-18', ['Podkarpackie Voivodeship', 'Województwo podkarpackie', 'PK']],
  ['PL-20', ['Podlaskie Voivodeship', 'Województwo podlaskie', 'Województwo podlaskie', 'PD']],
  ['PL-22', ['Pomeranian Voivodeship', 'Województwo pomorskie', 'PM']],
  ['PL-28', ['Warmian-Masurian Voivodeship', 'Województwo warmińsko-mazurskie', 'WN', 'WM']],
  ['PL-30', ['Greater Poland Voivodeship', 'Województwo wielkopolskie', 'WP', 'MP']],
  ['PL-32', ['West Pomeranian Voivodeship', 'Województwo zachodniopomorskie', 'ZP']],
  ['PL-10', ['Łódź Voivodeship', 'Województwo łódzkie', 'LD']],
  ['PL-24', ['Silesian Voivodeship', 'Województwo śląskie', 'SL']],
  ['PL-26', ['Świętokrzyskie Voivodeship', 'Województwo świętokrzyskie', 'SK', 'SW']],
  ['CN-AH', ['An Hui Sheng', 'Anhui', '安徽省']],
  ['CN-MO', ['澳门', '澳门特别行政区']],
  ['CN-BJ', ['Bei Jing Shi', '北京市', 'Beijing']],
  ['CN-CQ', ['Chongqing', 'Chong Qing Shi', '重庆市']],
  ['CN-FJ', ['Fu Jian Sheng', 'Fujian', '福建省']],
  ['CN-GS', ['Gan Su Sheng', 'Gansu', '甘肃省']],
  ['CN-GD', ['Guang Dong Sheng', 'Guangdong', 'Guangxi Zhuang', 'Guangdong Province', '广东省']],
  ['CN-GX', ['Guang Xi Zhuang Zu Zi Zhi Qu', 'Guangxi', '广西壮族自治区']],
  ['CN-GZ', ['Gui Zhou Sheng', 'Guizhou', '贵州省']],
  ['CN-HI', ['Hai Nan Sheng', 'Hainan', '海南省']],
  ['CN-HE', ['He Bei Sheng', 'Hebei', '河北省']],
  ['CN-HL', ['Hei Long Jiang Sheng', 'Heilongjiang', '黑龙江省']],
  ['CN-HA', ['He Nan Sheng', 'Henan', '河南省']],
  ['CN-HK', ['Xianggang Tebiexingzhengqu', '香港', '香港特别行政区']],
  ['CN-HB', ['Hu Bei Sheng', 'Hubei', '湖北省']],
  ['CN-HN', ['Hu Nan Sheng', 'Hunan', '湖南省']],
  ['CN-JS', ['Jiang Su Sheng', 'Jiangsu', '江苏省']],
  ['CN-JX', ['Jiang Xi Sheng', 'Jiangxi', '江西省']],
  ['CN-JL', ['Ji Lin Sheng', 'Jilin', '吉林省']],
  ['CN-LN', ['Liao Ning Sheng', 'Liaoning', '辽宁省']],
  ['CN-NM', ['Nei Meng Gu Zi Zhi Qu', 'Inner Mongolia', '内蒙古', '内蒙古自治区']],
  ['CN-NX', ['Ningxia', 'Ningxia Hui', '宁夏回族自治区', '宁夏']],
  ['CN-QH', ['Qing Hai Sheng', 'Qinghai', '青海省']],
  ['CN-SN', ['Shaanxi', '陕西省']],
  ['CN-SD', ['Shan Dong Sheng', 'Shandong', '山东省']],
  ['CN-SH', ['Shang Hai Shi', 'Shanghai', '上海市']],
  ['CN-SX', ['Shan Xi Sheng', 'Shanxi', '山西省']],
  ['CN-SC', ['Si Chuan Sheng', 'Sichuan', '四川省']],
  ['CN-TW', ['台湾', '台湾省']],
  ['CN-TJ', ['Tian Jin Shi', 'Tianjin', '天津市']],
  ['CN-XJ', ['Xinjiang', 'Xin Jiang Wei Wu Er Zi Zhi Qu', 'Xinjiang Uygur', '新疆', '新疆维吾尔自治区']],
  ['CN-XZ', ['Xizang Zizhiqu', 'Tibet', '西藏', '西藏自治区']],
  ['CN-YN', ['Yun Nan Sheng', 'Yunnan', '云南省']],
  ['CN-ZJ', ['Zhe Jiang Sheng', 'Zhejiang', '浙江省']],
  ['VN-68', ['Phu Tho', 'Phu Tho Province']],
  ['VN-04', ['Cao Bang']],
  ['VN-31', ['Binh Dinh']],
  ['VN-70', ['Vinh Phuc']],
  ['VN-63', ['Ha Nam']],
  ['VN-39', ['Dong Nai']],
  ['VN-49', ['Vinh Long']],
  ['VN-69', ['Thai Nguyen']],
  ['VN-57', ['Binh Duong']],
  ['VN-DN', ['Da Nang', 'Da Nang City']],
  ['VN-46', ['Tien Giang']],
  ['VN-13', ['Quang Ninh']],
  ['VN-26', ['Thừa Thiên Huế', 'Thua Thien Hue']],
  ['VN-21', ['Thanh Hoá', 'Thanh Hoa']],
  ['VN-34', ['Khanh Hoa']],
  ['VN-05', ['Son La']],
  ['VN-72', ['Dak Nong']],
  ['VN-14', ['Hoa Binh']],
  ['VN-HN', ['Hanoi']],
  ['VN-24', ['Quang Binh', 'Quang Binh Province']],
  ['VN-50', ['Ben Tre']],
  ['VN-01', ['Lai Chau']],
  ['VN-66', ['Hung Yen']],
  ['VN-32', ['Phu Yen']],
  ['VN-43', ['Ba Ria - Vung Tau', 'Ba Ria-Vung Tau']],
  ['VN-35', ['Lam Dong']],
  ['VN-22', ['Nghe An']],
  ['VN-73', ['Hau Giang']],
  ['VN-56', ['Bac Ninh', 'Bac Ninh Province']],
  ['VN-58', ['Binh Phuoc']],
  ['VN-45', ['Dong Thap']],
  ['VN-59', ['Ca Mau']],
  ['VN-33', ['Dak Lak']],
  ['VN-SG', ['Ho Chi Minh City', 'Thành phố Hồ Chí Minh', 'TP. Hồ Chí Minh']],
  ['VN-40', ['Binh Thuan']],
  ['VN-18', ['Ninh Binh']],
  ['VN-36', ['Ninh Thuan']],
  ['VN-29', ['Quang Ngai']],
  ['VN-51', ['Tra Vinh']],
  ['VN-61', ['Hai Duong']],
  ['VN-03', ['Ha Giang']],
  ['VN-23', ['Ha Tinh']],
  ['VN-HP', ['Haiphong', 'Hai Phong', 'Hai Phong City']],
  ['VN-09', ['Lang Son']],
  ['VN-67', ['Nam Dinh']],
  ['VN-20', ['Thai Binh']],
  ['VN-CT', ['Can Tho']],
  ['VN-02', ['Lao Cai']],
  ['VN-71', ['Dien Bien']],
  ['VN-27', ['Quang Nam']],
  ['VN-25', ['Quang Tri']],
  ['VN-52', ['Soc Trang']],
  ['VN-54', ['Bac Giang']],
  ['VN-55', ['Bac Lieu']],
  ['VN-37', ['Tay Ninh']],
  ['VN-47', ['Kiên Giang', 'Kien Giang']],
  ['UA-43', ['Crimea']],
  ['UA-71', ['Cherkasy Oblast', "Cherkas'ka oblast", 'Cherkasy']],
  ['UA-74', ['Chernihiv Oblast', 'Chernihivska oblast', 'Chernihiv']],
  ['UA-77', ["Chernivets'ka oblast", 'Chernivtsi Oblast', 'Chernivtsi']],
  ['UA-12', [
    "Dnipropetrovs'ka oblast",
    'Dnipropetrovsk Oblast',
    'Dnipropetrovsk'
  ]],
  ['UA-14', ["Donets'ka oblast", 'Donetsk Oblast', 'Donetsk']],
  ['UA-26', [
    "Ivano-Frankivs'ka oblast",
    'Ivano-Frankivsk Oblast',
    'Ivano-Frankivsk'
  ]],
  ['UA-63', ['Kharkiv Oblast', "Kharkivs'ka oblast", 'Kharkiv']],
  ['UA-65', ["Khersons'ka oblast", 'Kherson Oblast', 'Kherson']],
  ['UA-68', ['Khmelnytskyi Oblast', 'Khmelnytska oblast', 'Khmelnytsky']],
  ['UA-35', ['Kirovohrad Oblast', 'Kirovohrad']],
  ['UA-30', ['Kyiv']],
  ['UA-32', ["Kyivs'ka oblast", 'Kyiv Oblast']],
  ['UA-09', ["Luhans'ka oblast", 'Luhansk Oblast', 'Luhansk']],
  ['UA-46', ['Lviv Oblast', "L'vivs'ka oblast", 'Lviv']],
  ['UA-48', ["Mykolaivs'ka oblast", 'Mykolayiv', 'Mykolaiv Oblast']],
  ['UA-51', ['Odesa Oblast', "Odes'ka oblast", 'Odessa']],
  ['UA-53', ["Poltavs'ka oblast", 'Poltava Oblast', 'Poltava']],
  ['UA-56', ['Rivne Oblast', "Rivnens'ka oblast", 'Rivne']],
  ['UA-40', ['Sevastopol']],
  ['UA-59', ['Sumy Oblast', "Sums'ka oblast", 'Sumy']],
  ['UA-61', ['Ternopil Oblast', "Ternopil's'ka oblast", 'Ternopil']],
  ['UA-05', ['Vinnytsia Oblast', "Vinnyts'ka oblast", 'Vinnytsya']],
  ['UA-07', ['Volyn Oblast', "Volyns'ka oblast", 'Volyn']],
  ['UA-21', ['Zakarpattia Oblast', "Zakarpats'ka oblast", 'Zakarpattya']],
  ['UA-23', ['Zaporizhia Oblast', "Zaporiz'ka oblast", 'Zaporizhzhya']],
  ['UA-18', ['Zhytomyr Oblast', "Zhytomyrs'ka oblast", 'Zhytomyr']],
  ['RO-BH', ['Județul Bihor', 'Bihor County']],
  ['RO-IL', ['Ialomița County', 'Ialomiţa']],
  ['RO-BT', ['Botoşani', 'Botoșani County']],
  ['RO-BN', ['Bistriţa-Năsăud', 'Bistrița-Năsăud County', 'Județul Bistrița-Năsăud']],
  ['RO-CV', ['Covasna County']],
  ['RO-MS', ['Mureş']],
  ['RO-SV', ['Suceava County']],
  ['RO-TM', ['Județul Timiș', 'Timiş', 'Timiș County']],
  ['RO-CJ', ['Județul Cluj', 'Cluj County']],
  ['RO-NT', ['Neamţ', 'Neamț County']],
  ['RO-IF', ['Județul Ilfov', 'Ilfov County']],
  ['RO-PH', ['Județul Prahova', 'Prahova County']],
  ['RO-HR', ['Harghita County', 'Județul Harghita']],
  ['RO-GR', ['Giurgiu County']],
  ['RO-IS', ['Județul Iași', 'Iaşi', 'Iași County']],
  ['RO-MH', ['Mehedinți County']],
  ['RO-GL', ['Galaţi']],
  ['RO-BZ', ['Buzău County']],
  ['RO-HD', ['Județul Hunedoara']],
  ['RO-MM', ['Maramureş', 'Maramureș']],
  ['RO-SB', ['Județul Sibiu']],
  ['RO-BV', ['Braşov', 'Brașov', 'Județul Brașov']],
  ['RO-AB', ['Alba County', 'Județul Alba']],
  ['RO-VS', ['Vaslui County']],
  ['RO-DJ', ['Dolj County', 'Județul Dolj']],
  ['RO-CS', ['Caraș-Severin County']],
  ['RO-AG', ['Argeş', 'Județul Argeș']],
  ['RO-CT', ['Constanţa', 'Județul Constanța']],
  ['RO-GJ', ['Gorj County']],
  ['RO-DB', ['Dîmboviţa', 'Dâmbovița']],
  ['RO-B', ['Bucharest']],
  ['RO-BC', ['Bacău County']],
  ['RO-CL', ['Călăraşi', 'Călărași County']],
  ['RO-OT', ['Olt County']],
  ['RO-VL', ['Vâlcea County']],
  ['RU-AD', ['Adygea', 'Adygea Republic']],
  ['RU-AL', ['Altay', 'Altai Republic']],
  ['RU-ALT', ['Altayskiy kray', 'Altai Krai']],
  ['RU-AMU', ["Amurskaya oblast'", 'Amur Oblast', 'Amur']],
  ['RU-ARK', ["Arkhangel'skaya oblast'", 'Arkhangelsk Oblast', "Arkhangel'sk", 'Arkhangel’sk']],
  ['RU-AST', ["Astrakhanskaya oblast'", 'Astrakhan Oblast', 'Astrakhan', 'Astrakhan’']],
  ['RU-BA', ['Baškortostan', 'Respublika Bashkortostan', 'Republic of Bashkortostan']],
  ['RU-BEL', ["Belgorodskaya oblast'", 'Belgorod Oblast', 'Belgorod']],
  ['RU-BRY', ["Bryanskaya oblast'", 'Bryansk Oblast', 'Bryansk']],
  ['RU-BU', ['Buryatiya', 'Buryatia']],
  ['RU-CE', ['Čečenskaja Respublika', 'Chechnya']],
  ['RU-CHE', ["Čeljabinskaja oblast'", 'Chelyabinsk Oblast', 'Chelyabinsk']],
  ['RU-CHU', ['Čukotskij avtonomnyj okrug', 'Chukot']],
  ['RU-CU', ['Čuvašskaja Respublika', 'Chuvashia Republic', 'Chuvashia']],
  ['RU-DA', ['Dagestan', 'Republic of Dagestan']],
  ['RU-YEV', ["Yevreyskaya avtonomnaya oblast'", 'Jewish Autonomous Oblast']],
  ['RU-KHA', ['Khabarovskiy kray', 'Khabarovsk Krai', 'Khabarovsk']],
  ['RU-KK', ['Khakasiya', 'Republic of Khakassia', 'Khakassia']],
  ['RU-KHM', ['Khanty-Mansiyskiy avtonomnyy okrug', 'Khanty-Mansi Autonomous Okrug', 'Khanty-Mansi']],
  ['RU-IN', ['Ingušetija', 'Ingushetia']],
  ['RU-IRK', ["Irkutskaya oblast'", 'Irkutsk Oblast', 'Irkutsk']],
  ['RU-IVA', ["Ivanovskaya oblast'", 'Ivanovo Oblast', 'Ivanovo']],
  ['RU-YAN', ['Yamalo-Nenetskiy avtonomnyy okrug', 'Yamalo-Nenets', 'Yamalo-Nenets Autonomous Okrug']],
  ['RU-YAR', ["Yaroslavskaya oblast'", 'Yaroslavl Oblast', 'Yaroslavl', 'Yaroslavl’']],
  ['RU-KB', ['Kabardino-Balkarskaya Respublika', 'Kabardino-Balkaria', 'Kabardino-Balkarian Republic']],
  ['RU-KGD', ["Kaliningradskaya oblast'", 'Kaliningrad Oblast', 'Kaliningrad']],
  ['RU-KL', ['Kalmykiya', 'Republic of Kalmykia', 'Kalmykia']],
  ['RU-KLU', ["Kalužskaja oblast'", 'Kaluga Oblast', 'Kaluga']],
  ['RU-KAM', ['Kamčatskij kraj', 'Kamchatka Krai', 'Kamchatka']],
  ['RU-KC', ['Karačaevo-Čerkesskaja Respublika', 'Karachay-Cherkessia']],
  ['RU-KR', ['Kareliya', 'Republic of Karelia', 'Karelia']],
  ['RU-KEM', ["Kemerovskaya oblast'", 'Kemerovo Oblast', 'Kemerovo']],
  ['RU-KIR', ["Kirovskaya oblast'", 'Kirov Oblast', 'Kirov']],
  ['RU-KO', ['Komi', 'Respúblika Kómi', 'Komi-Permyak']],
  ['RU-KOS', ["Kostromskaya oblast'", 'Kostroma Oblast', 'Kostroma']],
  ['RU-KDA', ['Krasnodarskiy kray', 'Krasnodar Krai', 'Krasnodar']],
  ['RU-KYA', ['Krasnoyarskiy kray', 'Krasnoyarsk Krai']],
  ['RU-KGN', ["Kurganskaya oblast'", 'Kurgan Oblast', 'Kurgan']],
  ['RU-KRS', ["Kurskaya oblast'", 'Kursk Oblast', 'Kursk']],
  ['RU-LEN', ["Leningradskaya oblast'", 'Leningrad Oblast', 'Leningrad']],
  ['RU-LIP', ["Lipetskaya oblast'", 'Lipetsk Oblast', 'Lipetsk']],
  ['RU-MAG', ["Magadanskaya oblast'", 'Magadan Oblast']],
  ['RU-ME', ['Mariy El', 'Mari El Republic', 'Mari El']],
  ['RU-MO', ['Mordoviya', 'Mordovia Republic', 'Mordovia']],
  ['RU-MOS', ["Moskovskaya oblast'", 'Moscow Oblast', 'Moscow']],
  ['RU-MOW', ['Moskva', 'Moscow City', 'Москва']],
  ['RU-MUR', ["Murmanskaya oblast'", 'Murmansk Oblast', 'Murmansk']],
  ['RU-NEN', ['Nenetskiy avtonomnyy okrug', 'Nenets Autonomous Okrug']],
  ['RU-NIZ', ["Nižegorodskaja oblast'", 'Nizhny Novgorod Oblast', 'Nizhniy Novgorod']],
  ['RU-NGR', ["Novgorodskaya oblast'", 'Novgorod Oblast', 'Novgorod']],
  ['RU-NVS', ["Novosibirskaya oblast'", 'Novosibirsk Oblast', 'Novosibirsk']],
  ['RU-OMS', ["Omskaya oblast'", 'Omsk Oblast', 'Omsk']],
  ['RU-ORE', ["Orenburgskaya oblast'", 'Orenburg Oblast', 'Orenburg']],
  ['RU-ORL', ["Orlovskaya oblast'", 'Oryol Oblast', 'Orel']],
  ['RU-PNZ', ["Penzenskaya oblast'", 'Penza Oblast', 'Penza']],
  ['RU-PER', ['Permskiy kray', 'Perm Krai', 'Perm']],
  ['RU-PRI', ['Primorskiy kray', 'Primorsky Krai', 'Primorye']],
  ['RU-PSK', ["Pskovskaya oblast'", 'Pskov Oblast', 'Pskov']],
  ['RU-RYA', ["Ryazanskaya oblast'", 'Ryazan Oblast', "Ryazan'", 'Ryazan’']],
  ['RU-ROS', ["Rostovskaya oblast'", 'Rostov Oblast', 'Rostov']],
  ['RU-SA', ['Sakha', 'Respublika Sakha (Yakutiya)']],
  ['RU-SAK', ["Sakhalinskaya oblast'", 'Sakhalin Oblast', 'Sakhalin']],
  ['RU-SAM', ["Samarskaya oblast'", 'Samara Oblast', 'Samara']],
  ['RU-SPE', [
    'Sankt-Peterburg',
    'St Petersburg City',
    'Saint Petersburg',
    'Санкт-Петербург',
    'St. Petersburg City'
  ]],
  ['RU-SAR', ["Saratovskaya oblast'", 'Saratov Oblast', 'Saratov']],
  ['RU-SE', ['Severnaya Osetiya', 'North Ossetia–Alania Republic', 'Respublika Severnaya Osetiya — Alaniya', 'North Ossetia-Alania']],
  ['RU-SMO', ["Smolenskaya oblast'", 'Smolensk Oblast', 'Smolensk']],
  ['RU-STA', ["Stavropol'skiy kray", 'Stavropol Krai', 'Stavropol', 'Stavropolskiy kray']],
  ['RU-SVE', ["Sverdlovskaya oblast'", 'Sverdlovsk Oblast', 'Sverdlovsk']],
  ['RU-TAM', ["Tambovskaya oblast'", 'Tambov Oblast', 'Tambov']],
  ['RU-TA', ['Tatarstan', 'Respublika Tatarstan', 'Republic of Tatarstan']],
  ['RU-TYU', ["Tyumenskaya oblast'", 'Tyumen Oblast', "Tyumen'", 'Evenki', 'Tyumen', 'Tyumen’']],
  ['RU-TOM', ["Tomskaya oblast'", 'Tomsk Oblast', 'Magadan', 'Tomsk']],
  ['RU-TUL', ["Tul'skaya oblast'", 'Tula Oblast', "Tulskaya oblast'", 'Tula']],
  ['RU-TVE', ["Tverskaya oblast'", 'Tver Oblast', 'Tver', 'Tver’']],
  ['RU-TY', ['Tyva', 'Republic of Tyva']],
  ['RU-UD', ['Udmurtskaya Respublika', 'Udmurt Republic', 'Udmurtia']],
  ['RU-ULY', ["Ul'yanovskaya oblast'", 'Ulyanovsk Oblast', "Ul'yanovsk", 'Ul’yanovsk']],
  ['RU-VLA', ["Vladimirskaya oblast'", 'Vladimir Oblast', 'Vladimir']],
  ['RU-VGG', ["Volgogradskaya oblast'", 'Volgograd Oblast', 'Volgograd']],
  ['RU-VLG', ["Vologodskaya oblast'", 'Vologda Oblast', 'Vologda']],
  ['RU-VOR', ["Voronežskaja oblast'", 'Voronezh Oblast', 'Voronezh']],
  ['RU-ZAB', ["Zabaykal'skiy kray", 'Zabaykalsky Krai']]
]);
